name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.10.0

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: ng build ngx-weather

      - name: Publish to npm
        run: npm publish ./dist/ngx-weather
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
